import io
from datetime import datetime
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.chart import LineChart, BarChart, PieChart, Reference

# =========================================================
# ENTERPRISE COLOR PALETTE & STYLES
# =========================================================
COLOR_NAVY_DARK = "0F172A"
COLOR_NAVY_MED = "1E293B"
COLOR_BLUE_HEADER = "1E3A8A"
COLOR_BLUE_ACCENT = "2563EB"
COLOR_BG_LIGHT = "F8FAFC"
COLOR_CARD_BG = "F1F5F9"
COLOR_BORDER = "CBD5E1"
COLOR_TEXT_MUTED = "64748B"

FONT_TITLE = Font(name="Calibri", size=16, bold=True, color="FFFFFF")
FONT_SUBTITLE = Font(name="Calibri", size=10, italic=True, color="E2E8F0")
FONT_SECTION = Font(name="Calibri", size=12, bold=True, color="FFFFFF")
FONT_HEADER = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
FONT_BOLD = Font(name="Calibri", size=11, bold=True, color="0F172A")
FONT_REGULAR = Font(name="Calibri", size=10, color="0F172A")

FONT_KPI_LABEL = Font(name="Calibri", size=9, bold=True, color=COLOR_TEXT_MUTED)
FONT_KPI_VAL = Font(name="Calibri", size=16, bold=True, color="1E3A8A")

FILL_TITLE = PatternFill(start_color=COLOR_NAVY_DARK, end_color=COLOR_NAVY_DARK, fill_type="solid")
FILL_SECTION = PatternFill(start_color=COLOR_NAVY_MED, end_color=COLOR_NAVY_MED, fill_type="solid")
FILL_HEADER = PatternFill(start_color=COLOR_BLUE_HEADER, end_color=COLOR_BLUE_HEADER, fill_type="solid")
FILL_ZEBRA_EVEN = PatternFill(start_color=COLOR_BG_LIGHT, end_color=COLOR_BG_LIGHT, fill_type="solid")
FILL_ZEBRA_ODD = PatternFill(start_color="FFFFFF", end_color="FFFFFF", fill_type="solid")
FILL_KPI_CARD = PatternFill(start_color=COLOR_CARD_BG, end_color=COLOR_CARD_BG, fill_type="solid")

THIN_SIDE = Side(border_style="thin", color=COLOR_BORDER)
BORDER_CELL = Border(left=THIN_SIDE, right=THIN_SIDE, top=THIN_SIDE, bottom=THIN_SIDE)
BORDER_BOX = Border(
    left=Side(border_style="medium", color=COLOR_BLUE_HEADER),
    right=Side(border_style="medium", color=COLOR_BLUE_HEADER),
    top=Side(border_style="medium", color=COLOR_BLUE_HEADER),
    bottom=Side(border_style="medium", color=COLOR_BLUE_HEADER)
)

ALIGN_CENTER = Alignment(horizontal="center", vertical="center")
ALIGN_LEFT = Alignment(horizontal="left", vertical="center")
ALIGN_RIGHT = Alignment(horizontal="right", vertical="center")


def _autofit_columns(ws, min_width=12):
    for col in ws.columns:
        max_len = 0
        col_letter = get_column_letter(col[0].column)
        for cell in col:
            if cell.value is not None:
                val_str = str(cell.value)
                max_len = max(max_len, len(val_str))
        ws.column_dimensions[col_letter].width = max(max_len + 4, min_width)


def _add_company_header(ws, title_text, subtitle_text="", end_col=8):
    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=end_col)
    cell1 = ws.cell(row=1, column=1, value="Crescent Steel & Allied Products Ltd. | Factory PPE Monitoring System")
    cell1.font = Font(name="Calibri", size=10, bold=True, color="94A3B8")
    cell1.fill = FILL_TITLE
    cell1.alignment = ALIGN_LEFT

    ws.merge_cells(start_row=2, start_column=1, end_row=2, end_column=end_col)
    cell2 = ws.cell(row=2, column=1, value=title_text.upper())
    cell2.font = FONT_TITLE
    cell2.fill = FILL_TITLE
    cell2.alignment = ALIGN_LEFT

    ws.merge_cells(start_row=3, start_column=1, end_row=3, end_column=end_col)
    sub_val = f"Generated On: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  |  {subtitle_text}" if subtitle_text else f"Generated On: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    cell3 = ws.cell(row=3, column=1, value=sub_val)
    cell3.font = FONT_SUBTITLE
    cell3.fill = FILL_TITLE
    cell3.alignment = ALIGN_LEFT

    ws.row_dimensions[1].height = 20
    ws.row_dimensions[2].height = 28
    ws.row_dimensions[3].height = 20


# =========================================================
# 1. DAILY HSE SUMMARY REPORT
# =========================================================
def generate_daily_summary_excel(report_data, generated_by="HSE Officer"):
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Daily Summary"
    ws.views.sheetView[0].showGridLines = True

    _add_company_header(
        ws,
        title_text="Daily HSE Summary Report",
        subtitle_text=f"Report Date: {report_data.get('date', 'N/A')} | Generated By: {generated_by}",
        end_col=7
    )

    # KPI Section (Row 5 - 6)
    kpis = [
        ("Total Incidents", report_data.get("todays_incidents", 0)),
        ("Active Violations", report_data.get("active_incidents", 0)),
        ("Resolved Incidents", report_data.get("completed_incidents", 0)),
        ("Workers Monitored", report_data.get("total_workers", 0)),
        ("Compliance Rate", f"{report_data.get('compliance_rate', 0)}%"),
        ("Avg Resolution Time", f"{report_data.get('avg_duration', 0)}s"),
        ("Highest Risk Zone", report_data.get("highest_risk_zone", "None")),
    ]

    for idx, (label, val) in enumerate(kpis, start=1):
        lbl_cell = ws.cell(row=5, column=idx, value=label)
        lbl_cell.font = FONT_KPI_LABEL
        lbl_cell.fill = FILL_KPI_CARD
        lbl_cell.alignment = ALIGN_CENTER
        lbl_cell.border = BORDER_CELL

        val_cell = ws.cell(row=6, column=idx, value=val)
        val_cell.font = FONT_KPI_VAL
        val_cell.fill = FILL_KPI_CARD
        val_cell.alignment = ALIGN_CENTER
        val_cell.border = BORDER_CELL

    # Executive Summary Paragraph (Row 8)
    ws.merge_cells("A8:G8")
    sec_cell = ws.cell(row=8, column=1, value="EXECUTIVE SUMMARY")
    sec_cell.font = FONT_SECTION
    sec_cell.fill = FILL_SECTION
    sec_cell.alignment = ALIGN_LEFT

    ws.merge_cells("A9:G9")
    sum_cell = ws.cell(row=9, column=1, value=report_data.get("executive_summary", "No summary available."))
    sum_cell.font = FONT_REGULAR
    sum_cell.alignment = Alignment(horizontal="left", vertical="center", wrap_text=True)

    # Hourly Distribution & Zone Breakdown (Row 11)
    ws.merge_cells("A11:C11")
    ws.cell(row=11, column=1, value="24-HOUR INCIDENT BREAKDOWN").font = FONT_SECTION
    ws.cell(row=11, column=1).fill = FILL_SECTION

    ws.merge_cells("E11:G11")
    ws.cell(row=11, column=5, value="ZONE SAFETY MATRIX").font = FONT_SECTION
    ws.cell(row=11, column=5).fill = FILL_SECTION

    # Table Headers (Row 12)
    h1 = ws.cell(row=12, column=1, value="Hour")
    h2 = ws.cell(row=12, column=2, value="Incidents Logged")
    for h in [h1, h2]:
        h.font = FONT_HEADER
        h.fill = FILL_HEADER
        h.alignment = ALIGN_CENTER

    z_headers = ["Zone", "Monitored Workers", "Violations Logged"]
    for z_idx, z_h in enumerate(z_headers, start=5):
        cell = ws.cell(row=12, column=z_idx, value=z_h)
        cell.font = FONT_HEADER
        cell.fill = FILL_HEADER
        cell.alignment = ALIGN_CENTER

    # Hourly Data Rows
    hourly_list = report_data.get("hourly_breakdown", [])
    for r_idx, item in enumerate(hourly_list, start=13):
        c1 = ws.cell(row=r_idx, column=1, value=item.get("hour", ""))
        c2 = ws.cell(row=r_idx, column=2, value=item.get("count", 0))
        fill = FILL_ZEBRA_EVEN if r_idx % 2 == 0 else FILL_ZEBRA_ODD
        c1.fill = fill
        c2.fill = fill
        c1.alignment = ALIGN_CENTER
        c2.alignment = ALIGN_CENTER
        c1.border = BORDER_CELL
        c2.border = BORDER_CELL

    # Zone Data Rows
    zone_matrix = report_data.get("zone_matrix", [])
    for zm_idx, zm in enumerate(zone_matrix, start=13):
        zc1 = ws.cell(row=zm_idx, column=5, value=zm.get("zone", "Unknown"))
        zc2 = ws.cell(row=zm_idx, column=6, value=zm.get("total_workers", 0))
        zc3 = ws.cell(row=zm_idx, column=7, value=zm.get("violations", 0))
        fill = FILL_ZEBRA_EVEN if zm_idx % 2 == 0 else FILL_ZEBRA_ODD
        for zc in [zc1, zc2, zc3]:
            zc.fill = fill
            zc.alignment = ALIGN_CENTER
            zc.border = BORDER_CELL
            zc.font = FONT_REGULAR

    # Top Incidents Section (Row 38)
    ws.merge_cells("A38:G38")
    ws.cell(row=38, column=1, value="TOP INCIDENTS LOGGED TODAY").font = FONT_SECTION
    ws.cell(row=38, column=1).fill = FILL_SECTION

    top_cols = ["ID", "Track ID", "Timestamp", "Zone", "Violation Type", "Duration (s)", "Status"]
    for c_idx, col_name in enumerate(top_cols, start=1):
        c = ws.cell(row=39, column=c_idx, value=col_name)
        c.font = FONT_HEADER
        c.fill = FILL_HEADER
        c.alignment = ALIGN_CENTER

    top_incidents = report_data.get("top_incidents", [])
    for t_idx, inc in enumerate(top_incidents, start=40):
        row_cells = [
            ws.cell(row=t_idx, column=1, value=inc.get("id")),
            ws.cell(row=t_idx, column=2, value=f"#{inc.get('track_id', 'N/A')}"),
            ws.cell(row=t_idx, column=3, value=inc.get("timestamp")),
            ws.cell(row=t_idx, column=4, value=inc.get("zone")),
            ws.cell(row=t_idx, column=5, value=inc.get("event_type")),
            ws.cell(row=t_idx, column=6, value=inc.get("duration")),
            ws.cell(row=t_idx, column=7, value="Resolved" if inc.get("status") in ["Completed", "Resolved"] or inc.get("resolved") == 1 else "Active"),
        ]
        fill = FILL_ZEBRA_EVEN if t_idx % 2 == 0 else FILL_ZEBRA_ODD
        for cell in row_cells:
            cell.fill = fill
            cell.alignment = ALIGN_CENTER
            cell.border = BORDER_CELL
            cell.font = FONT_REGULAR

    _autofit_columns(ws)
    output = io.BytesIO()
    wb.save(output)
    output.seek(0)
    return output.getvalue()


# =========================================================
# 2. INCIDENT INVESTIGATION REPORT
# =========================================================
def generate_incident_investigation_excel(report_data, filters=None, generated_by="HSE Officer"):
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Incident Investigation"
    ws.views.sheetView[0].showGridLines = True

    filters = filters or {}
    start_d = filters.get("start_date") or "Beginning"
    end_d = filters.get("end_date") or "Today"
    z_f = filters.get("zone") or "All Zones"
    e_f = filters.get("event_type") or "All Types"
    s_f = filters.get("status") or "All Statuses"

    _add_company_header(
        ws,
        title_text="Incident Investigation Detailed Report",
        subtitle_text=f"Scope: {start_d} to {end_d}  |  Generated By: {generated_by}",
        end_col=10
    )

    # Filter Audit Block (Rows 5 - 6)
    filter_items = [
        ("Date Range", f"{start_d} to {end_d}"),
        ("Zone Filter", z_f),
        ("Violation Category", e_f),
        ("Status Scope", "Resolved Only" if s_f in ["Completed", "Resolved"] else s_f),
        ("Total Incidents", report_data.get("total_matching", len(report_data.get("incidents", [])))),
    ]

    for idx, (flbl, fval) in enumerate(filter_items, start=1):
        fc1 = ws.cell(row=5, column=idx, value=flbl)
        fc1.font = FONT_KPI_LABEL
        fc1.fill = FILL_KPI_CARD
        fc1.alignment = ALIGN_CENTER
        fc1.border = BORDER_CELL

        fc2 = ws.cell(row=6, column=idx, value=fval)
        fc2.font = FONT_BOLD
        fc2.fill = FILL_KPI_CARD
        fc2.alignment = ALIGN_CENTER
        fc2.border = BORDER_CELL

    # Incident Table Headers (Row 8)
    headers = [
        "Incident ID", "Track ID", "Zone", "Violation Type",
        "Start Time", "End Time", "Duration (s)", "Status",
        "Snapshot", "Video Clip"
    ]

    ws.row_dimensions[8].height = 25
    for c_idx, h_text in enumerate(headers, start=1):
        cell = ws.cell(row=8, column=c_idx, value=h_text)
        cell.font = FONT_HEADER
        cell.fill = FILL_HEADER
        cell.alignment = ALIGN_CENTER

    incidents = report_data.get("incidents", [])
    for r_idx, inc in enumerate(incidents, start=9):
        is_resolved = inc.get("resolved") == 1 or inc.get("status") in ["Completed", "Resolved"]
        dur_val = inc.get("duration", 0)
        if is_resolved and dur_val <= 0:
            dur_val = 1

        snap_str = "Available" if inc.get("snapshot_path") else "None"
        vid_str = "Available" if inc.get("video_path") else "None"

        row_vals = [
            inc.get("id"),
            f"#{inc.get('track_id', 'N/A')}",
            inc.get("zone", "Unknown"),
            inc.get("event_type", "Helmet Missing"),
            inc.get("start_time") or inc.get("timestamp"),
            inc.get("end_time") if is_resolved else "Ongoing",
            dur_val,
            "Resolved" if is_resolved else "Active",
            snap_str,
            vid_str
        ]

        fill = FILL_ZEBRA_EVEN if r_idx % 2 == 0 else FILL_ZEBRA_ODD
        for c_idx, val in enumerate(row_vals, start=1):
            cell = ws.cell(row=r_idx, column=c_idx, value=val)
            cell.fill = fill
            cell.font = FONT_REGULAR
            cell.alignment = ALIGN_CENTER
            cell.border = BORDER_CELL

    # AutoFilter & Freeze Panes
    last_row = max(len(incidents) + 8, 9)
    ws.auto_filter.ref = f"A8:J{last_row}"
    ws.freeze_panes = "A9"

    _autofit_columns(ws)
    output = io.BytesIO()
    wb.save(output)
    output.seek(0)
    return output.getvalue()


# =========================================================
# 3. EXECUTIVE ANALYTICS REPORT (MULTI-SHEET WORKBOOK)
# =========================================================
def generate_executive_analytics_excel(report_data, generated_by="Executive Management"):
    wb = openpyxl.Workbook()

    # ---------------------------------------------------------
    # Sheet 1: Executive Dashboard
    # ---------------------------------------------------------
    ws1 = wb.active
    ws1.title = "Executive Dashboard"
    ws1.views.sheetView[0].showGridLines = True

    _add_company_header(
        ws1,
        title_text="Executive Safety & Compliance Analytics Dashboard",
        subtitle_text=f"Scope: {report_data.get('start_date', 'Beginning')} to {report_data.get('end_date', 'Today')}  |  Generated By: {generated_by}",
        end_col=8
    )

    kpis = [
        ("Total Incidents", report_data.get("total_incidents", 0)),
        ("Active Violations", report_data.get("active_incidents", 0)),
        ("Resolved Incidents", report_data.get("completed_incidents", 0)),
        ("Compliance Rate", f"{report_data.get('compliance_rate', 0)}%"),
        ("Avg Resolution", f"{report_data.get('avg_duration', 0)}s"),
        ("Longest Incident", f"{report_data.get('longest_duration', 0)}s"),
        ("Highest Risk Zone", report_data.get("highest_risk_zone", "None")),
    ]

    for idx, (label, val) in enumerate(kpis, start=1):
        ws1.cell(row=5, column=idx, value=label).font = FONT_KPI_LABEL
        ws1.cell(row=5, column=idx).fill = FILL_KPI_CARD
        ws1.cell(row=5, column=idx).alignment = ALIGN_CENTER
        ws1.cell(row=5, column=idx).border = BORDER_CELL

        ws1.cell(row=6, column=idx, value=val).font = FONT_KPI_VAL
        ws1.cell(row=6, column=idx).fill = FILL_KPI_CARD
        ws1.cell(row=6, column=idx).alignment = ALIGN_CENTER
        ws1.cell(row=6, column=idx).border = BORDER_CELL

    ws1.merge_cells("A8:G8")
    sec = ws1.cell(row=8, column=1, value="MANAGEMENT EXECUTIVE SUMMARY")
    sec.font = FONT_SECTION
    sec.fill = FILL_SECTION

    ws1.merge_cells("A9:G11")
    exec_text = (
        f"During the evaluated scope ({report_data.get('start_date', 'Beginning')} to {report_data.get('end_date', 'Today')}), "
        f"a total of {report_data.get('total_incidents', 0)} safety incidents were recorded across production zones. "
        f"The current helmet compliance index stands at {report_data.get('compliance_rate', 0)}%. "
        f"The highest risk zone identified was '{report_data.get('highest_risk_zone', 'None')}' with average incident resolution time of {report_data.get('avg_duration', 0)} seconds."
    )
    st_cell = ws1.cell(row=9, column=1, value=exec_text)
    st_cell.font = FONT_REGULAR
    st_cell.alignment = Alignment(horizontal="left", vertical="top", wrap_text=True)

    _autofit_columns(ws1)

    # ---------------------------------------------------------
    # Sheet 2: Daily Trend (Table + LineChart)
    # ---------------------------------------------------------
    ws2 = wb.create_sheet(title="Daily Trend")
    ws2.views.sheetView[0].showGridLines = True
    _add_company_header(ws2, title_text="Daily Incident Volume Trend", end_col=4)

    ws2.cell(row=5, column=1, value="Date").font = FONT_HEADER
    ws2.cell(row=5, column=1).fill = FILL_HEADER
    ws2.cell(row=5, column=2, value="Incidents Logged").font = FONT_HEADER
    ws2.cell(row=5, column=2).fill = FILL_HEADER

    daily_data = report_data.get("daily_trend", [])
    for r_idx, d_item in enumerate(daily_data, start=6):
        dt_val = d_item.get("date") or d_item.get("day") or ""
        cnt_val = int(d_item.get("count", 0))
        ws2.cell(row=r_idx, column=1, value=dt_val).alignment = ALIGN_CENTER
        ws2.cell(row=r_idx, column=2, value=cnt_val).alignment = ALIGN_CENTER
        fill = FILL_ZEBRA_EVEN if r_idx % 2 == 0 else FILL_ZEBRA_ODD
        ws2.cell(row=r_idx, column=1).fill = fill
        ws2.cell(row=r_idx, column=2).fill = fill
        ws2.cell(row=r_idx, column=1).border = BORDER_CELL
        ws2.cell(row=r_idx, column=2).border = BORDER_CELL

    max_d_row = ws2.max_row
    if max_d_row >= 6:
        line_chart = LineChart()
        line_chart.title = "Daily Incident Volume Trend"
        line_chart.style = 13
        line_chart.y_axis.title = "Incident Volume"
        line_chart.x_axis.title = "Date"

        data_ref = Reference(ws2, min_col=2, min_row=5, max_row=max_d_row)
        cats_ref = Reference(ws2, min_col=1, min_row=6, max_row=max_d_row)
        line_chart.add_data(data_ref, titles_from_data=True)
        line_chart.set_categories(cats_ref)
        line_chart.width = 18
        line_chart.height = 10
        ws2.add_chart(line_chart, "D5")
    else:
        ws2.cell(row=5, column=4, value="No daily trend data available for selected scope").font = FONT_SUBTITLE

    _autofit_columns(ws2)

    # ---------------------------------------------------------
    # Sheet 3: Hourly Violations (Table + ColumnChart)
    # ---------------------------------------------------------
    ws3 = wb.create_sheet(title="Hourly Violations")
    ws3.views.sheetView[0].showGridLines = True
    _add_company_header(ws3, title_text="24-Hour Hourly Violation Distribution", end_col=4)

    ws3.cell(row=5, column=1, value="Hour").font = FONT_HEADER
    ws3.cell(row=5, column=1).fill = FILL_HEADER
    ws3.cell(row=5, column=2, value="Incidents Count").font = FONT_HEADER
    ws3.cell(row=5, column=2).fill = FILL_HEADER

    hourly_data = report_data.get("hourly_trend") or report_data.get("hourly_breakdown") or []
    for r_idx, h_item in enumerate(hourly_data, start=6):
        hr_val = str(h_item.get("hour", ""))
        cnt_val = int(h_item.get("count", 0))
        ws3.cell(row=r_idx, column=1, value=hr_val).alignment = ALIGN_CENTER
        ws3.cell(row=r_idx, column=2, value=cnt_val).alignment = ALIGN_CENTER
        fill = FILL_ZEBRA_EVEN if r_idx % 2 == 0 else FILL_ZEBRA_ODD
        ws3.cell(row=r_idx, column=1).fill = fill
        ws3.cell(row=r_idx, column=2).fill = fill
        ws3.cell(row=r_idx, column=1).border = BORDER_CELL
        ws3.cell(row=r_idx, column=2).border = BORDER_CELL

    max_h_row = ws3.max_row
    if max_h_row >= 6:
        bar_chart = BarChart()
        bar_chart.type = "col"
        bar_chart.style = 10
        bar_chart.title = "Hourly Violation Distribution (00:00 - 23:00)"
        bar_chart.y_axis.title = "Incidents Logged"
        bar_chart.x_axis.title = "Hour"

        h_data_ref = Reference(ws3, min_col=2, min_row=5, max_row=max_h_row)
        h_cats_ref = Reference(ws3, min_col=1, min_row=6, max_row=max_h_row)
        bar_chart.add_data(h_data_ref, titles_from_data=True)
        bar_chart.set_categories(h_cats_ref)
        bar_chart.width = 18
        bar_chart.height = 10
        ws3.add_chart(bar_chart, "D5")
    else:
        ws3.cell(row=5, column=4, value="No hourly violation data available for selected scope").font = FONT_SUBTITLE

    _autofit_columns(ws3)

    # ---------------------------------------------------------
    # Sheet 4: Zone Analytics (Table + Clustered BarChart)
    # ---------------------------------------------------------
    ws4 = wb.create_sheet(title="Zone Analytics")
    ws4.views.sheetView[0].showGridLines = True
    _add_company_header(ws4, title_text="Zone Worker Exposure & Risk Analytics", end_col=6)

    z_cols = ["Zone", "Monitored Workers", "Violations Logged", "Violation Rate (%)", "Risk Status"]
    for idx, z_col in enumerate(z_cols, start=1):
        c = ws4.cell(row=5, column=idx, value=z_col)
        c.font = FONT_HEADER
        c.fill = FILL_HEADER
        c.alignment = ALIGN_CENTER

    zone_matrix = report_data.get("zone_matrix") or report_data.get("zone_breakdown") or []
    for r_idx, zm in enumerate(zone_matrix, start=6):
        z_name = str(zm.get("zone", "Unknown"))
        w_val = int(zm.get("total_workers", zm.get("workers", 0)))
        v_val = int(zm.get("violations", zm.get("count", 0)))
        pct_val = zm.get("violation_pct", 0.0)
        stat_val = str(zm.get("risk_status", "Low Risk"))

        ws4.cell(row=r_idx, column=1, value=z_name).alignment = ALIGN_CENTER
        ws4.cell(row=r_idx, column=2, value=w_val).alignment = ALIGN_CENTER
        ws4.cell(row=r_idx, column=3, value=v_val).alignment = ALIGN_CENTER
        ws4.cell(row=r_idx, column=4, value=f"{pct_val}%").alignment = ALIGN_CENTER
        ws4.cell(row=r_idx, column=5, value=stat_val).alignment = ALIGN_CENTER

        fill = FILL_ZEBRA_EVEN if r_idx % 2 == 0 else FILL_ZEBRA_ODD
        for c_i in range(1, 6):
            ws4.cell(row=r_idx, column=c_i).fill = fill
            ws4.cell(row=r_idx, column=c_i).border = BORDER_CELL
            ws4.cell(row=r_idx, column=c_i).font = FONT_REGULAR

    max_z_row = ws4.max_row
    if max_z_row >= 6:
        z_chart = BarChart()
        z_chart.type = "col"
        z_chart.style = 11
        z_chart.title = "Zone Workers Monitored vs Violations Logged"
        z_chart.y_axis.title = "Count"
        z_chart.x_axis.title = "Zone"

        z_data_ref = Reference(ws4, min_col=2, max_col=3, min_row=5, max_row=max_z_row)
        z_cats_ref = Reference(ws4, min_col=1, min_row=6, max_row=max_z_row)
        z_chart.add_data(z_data_ref, titles_from_data=True)
        z_chart.set_categories(z_cats_ref)
        z_chart.width = 18
        z_chart.height = 10
        ws4.add_chart(z_chart, "F5")
    else:
        ws4.cell(row=5, column=6, value="No zone analytics data available for selected scope").font = FONT_SUBTITLE

    _autofit_columns(ws4)

    # ---------------------------------------------------------
    # Sheet 5: Violation Categories (Table + PieChart)
    # ---------------------------------------------------------
    ws5 = wb.create_sheet(title="Violation Categories")
    ws5.views.sheetView[0].showGridLines = True
    _add_company_header(ws5, title_text="Violation Category Breakdown", end_col=4)

    ws5.cell(row=5, column=1, value="Category").font = FONT_HEADER
    ws5.cell(row=5, column=1).fill = FILL_HEADER
    ws5.cell(row=5, column=2, value="Count").font = FONT_HEADER
    ws5.cell(row=5, column=2).fill = FILL_HEADER

    v_cats = report_data.get("violation_types") or report_data.get("violation_categories") or report_data.get("type_breakdown") or []
    if not v_cats and report_data.get("total_incidents", 0) > 0:
        v_cats = [{"type": "Helmet Missing", "count": report_data.get("total_incidents", 0)}]

    for r_idx, vc in enumerate(v_cats, start=6):
        c_name = str(vc.get("type") or vc.get("name") or "Helmet Missing")
        c_cnt = int(vc.get("count") or vc.get("value") or 0)

        ws5.cell(row=r_idx, column=1, value=c_name).alignment = ALIGN_CENTER
        ws5.cell(row=r_idx, column=2, value=c_cnt).alignment = ALIGN_CENTER
        fill = FILL_ZEBRA_EVEN if r_idx % 2 == 0 else FILL_ZEBRA_ODD
        ws5.cell(row=r_idx, column=1).fill = fill
        ws5.cell(row=r_idx, column=2).fill = fill
        ws5.cell(row=r_idx, column=1).border = BORDER_CELL
        ws5.cell(row=r_idx, column=2).border = BORDER_CELL

    max_vc_row = ws5.max_row
    if max_vc_row >= 6:
        pie = PieChart()
        pie.title = "Violation Category Breakdown"
        pie_data = Reference(ws5, min_col=2, min_row=5, max_row=max_vc_row)
        pie_labels = Reference(ws5, min_col=1, min_row=6, max_row=max_vc_row)
        pie.add_data(pie_data, titles_from_data=True)
        pie.set_categories(pie_labels)
        pie.width = 14
        pie.height = 9
        ws5.add_chart(pie, "D5")
    else:
        ws5.cell(row=5, column=4, value="No violation category data available for selected scope").font = FONT_SUBTITLE

    _autofit_columns(ws5)

    # ---------------------------------------------------------
    # Sheet 6: Incident Log (Table + AutoFilter + Freeze Row)
    # ---------------------------------------------------------
    ws6 = wb.create_sheet(title="Incident Log")
    ws6.views.sheetView[0].showGridLines = True
    _add_company_header(ws6, title_text="Complete Safety Incident Audit Log", end_col=9)

    log_headers = [
        "Incident ID", "Track ID", "Timestamp", "Zone",
        "Violation Type", "Start Time", "End Time", "Duration (s)", "Status"
    ]
    ws6.row_dimensions[5].height = 25
    for c_idx, h_text in enumerate(log_headers, start=1):
        cell = ws6.cell(row=5, column=c_idx, value=h_text)
        cell.font = FONT_HEADER
        cell.fill = FILL_HEADER
        cell.alignment = ALIGN_CENTER

    all_incidents = report_data.get("incidents_log", [])
    for r_idx, inc in enumerate(all_incidents, start=6):
        is_resolved = inc.get("resolved") == 1 or inc.get("status") in ["Completed", "Resolved"]
        dur_val = inc.get("duration", 0)
        if is_resolved and dur_val <= 0:
            dur_val = 1

        row_vals = [
            inc.get("id"),
            f"#{inc.get('track_id', 'N/A')}",
            inc.get("timestamp"),
            inc.get("zone", "Unknown"),
            inc.get("event_type", "Helmet Missing"),
            inc.get("start_time") or inc.get("timestamp"),
            inc.get("end_time") if is_resolved else "Ongoing",
            dur_val,
            "Resolved" if is_resolved else "Active"
        ]

        fill = FILL_ZEBRA_EVEN if r_idx % 2 == 0 else FILL_ZEBRA_ODD
        for c_idx, val in enumerate(row_vals, start=1):
            cell = ws6.cell(row=r_idx, column=c_idx, value=val)
            cell.fill = fill
            cell.font = FONT_REGULAR
            cell.alignment = ALIGN_CENTER
            cell.border = BORDER_CELL

    last_log_row = max(len(all_incidents) + 5, 6)
    ws6.auto_filter.ref = f"A5:I{last_log_row}"
    ws6.freeze_panes = "A6"

    _autofit_columns(ws6)

    output = io.BytesIO()
    wb.save(output)
    output.seek(0)
    return output.getvalue()
